Adding Readme on how to debug Apache Camel with the Vimspector
camel-tooling/camel-dap-client-vim pull request #2
Opened 2022-09-07 17:04 UTC by Navyashree0923

#### Highlights of the PR 
1. Created a gif image to show the preview of camel debugging with vimspector.
2. Updated Readme on how to debug camel with vimspector.

2022-09-08 06:51 UTC, apupier requested changes
several places where we can add syntax highlighting  for code block which will help readers https://www.markdownguide.org/extended-syntax/#syntax-highlighting

2022-09-08 06:51 UTC, apupier commented on README.md
> +Add  mvn command to the happy PATH:
happy PATH? I guess you mean the system PATH. (but maybe the system PATH is happy? :-D)

2022-09-08 06:51 UTC, apupier commented on README.md
> +  any jar files
```suggestion
- I found 2 releases of camel DAP server here - https://github.com/camel-tooling/camel-debug-adapter/tags but it doesn't contain  any jar files 
```

2022-09-08 06:51 UTC, apupier commented on README.md
> +  after the succesful completion of mvn command
no need to recompile from source. The jar file is available on Maven Central repository: https://repo1.maven.org/maven2/com/github/camel-tooling/camel-dap-server/0.4.0/camel-dap-server-0.4.0.jar
So these steps can be simplified

2022-09-08 06:51 UTC, apupier commented on README.md
> +cd ~/.vim/plugged/vimspector/gadgets/linux/.gadgets.d
You can use this notation so that it is better displayed
\```sh
cd ~/.vim/plugged/vimspector/gadgets/linux/.gadgets.d
\```

it will be rendered this way:

```sh
cd ~/.vim/plugged/vimspector/gadgets/linux/.gadgets.d
```


https://arcticicestudio.github.io/styleguide-markdown/rules/code.html#no-shell-code-dollar-sign

2022-09-08 06:51 UTC, apupier commented on README.md
> +- mvn camel:run -Pcamel.debug
use the \```sh notation will improve readability

2022-09-08 06:51 UTC, apupier commented on README.md
> +- vim src/main/java/org/apache/camel/example/MyBean.java
use the ```sh notation will improve readability

2022-09-08 06:51 UTC, apupier commented on README.md
> +- Add the following cotent inside `MyBean.java` file:
```suggestion
- Add the following content inside `MyBean.java` file:
```

2022-09-08 06:51 UTC, apupier commented on README.md
> +```
```suggestion
```java
```

2022-09-08 06:51 UTC, apupier commented on README.md
> +```
```suggestion
```java
```

2022-09-08 06:51 UTC, apupier commented on README.md
> +
nitpick: no need of these 2 empty lines

2022-09-08 06:51 UTC, apupier commented on README.md
> +```
I think you need to explain what is HUMAN mode. That the goal is to provide  keymapping to use controllers of the debugger more easily

2022-09-08 06:51 UTC, apupier commented on README.md
> +I just got the debug integration for camel in vim running using vimspector. In order to not forget the config, I decided to quickly compile this readme.
Providing a lnk for vimspector would help users to learn more about it. I guess a lot of them do not know what it is

2022-09-08 06:51 UTC, apupier commented on README.md
> +```
```suggestion
```json
```

2022-09-08 06:51 UTC, apupier commented on README.md
> + ```
```suggestion
 ```json
```

2022-09-08 09:21 UTC, apupier commented on README.md
> +        "/home/camel-debug-adapter-0.4.0/target/camel-dap-server-0.4.0.jar"
I think we can have it simpler like /home/camel-dap-server-0.4.0.jar

2022-09-08 09:22 UTC, apupier commented on README.md
> +  cd ~/camel-examples/examples/main
we need to explain somewhere in the readme from where the Camel example used is coming from

2022-09-08 13:05 UTC, apupier requested changes

2022-09-08 13:05 UTC, apupier commented on README.md
> +# How to get camel DAPserver.jar file?
```suggestion
# How to get Camel Debug Adapter server jar file?
```

2022-09-08 13:05 UTC, apupier commented on README.md
> +# Troubleshooting
wondering why it is called Troubleshooting. It is descriging some other steps to launch the applaiction and connect the Camel debugger

2022-09-08 17:54 UTC, Navyashree0923 commented on README.md
> +Add  mvn command to the happy PATH:
Thanks for the review. It is actually the system path and I thought they both were same. As per the discussion I've removed this from the Readme

2022-09-08 17:54 UTC, Navyashree0923 commented on README.md
> +  any jar files
Thank you

2022-09-08 17:55 UTC, Navyashree0923 commented on README.md
> +  after the succesful completion of mvn command
I've replaced the lines with the jar available in the maven repository. Thanks for pointing this

2022-09-08 17:55 UTC, Navyashree0923 commented on README.md
> +- mvn camel:run -Pcamel.debug
Thank you

2022-09-08 17:57 UTC, Navyashree0923 commented on README.md
> +# Troubleshooting
Thank you I have updated the changes to fix this

2022-09-08 17:58 UTC, Navyashree0923 commented
Thanks for the feedback. Can you please review it

2022-09-09 06:51 UTC, apupier approved these changes

2022-09-09 11:32 UTC, merged